name: gotify_client
description: A beautiful Gotify client for mobile
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  flutter_local_notifications: ^19.0.0
  logging: ^1.3.0
  web_socket_channel: ^3.0.2
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
