# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build, Format, Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_format_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up Flutter instead of Dart
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get

      # Verify the use of 'flutter format' on each commit.
      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze

      # Run tests without exposing sensitive information.
      - name: Run tests
        run: flutter test --coverage
